apiVersion: jsn.k8s.bgpat.net/v1beta1
kind: JobNotifier
metadata:
  name: jobnotifier-sample
spec:
  selector:
    matchLabels:
      role: job
  channels:
  - random
  mention_to:
  - bgpat
  - here
  min_fails: 1
