apiVersion: jsn.k8s.bgpat.net/v1beta1
kind: JobNotifier
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: jobnotifier-sample
spec:
  selector:
    matchLabels:
      role: job
  channels:
  - random
  mention_to:
  - bgpat
  - here
